### ISSUE TITLE
dotnet error

### ISSUE THREAD

**Issue by samaguire** [gbrueckl/PowerBI-VSCode#22] opened 2023-12-18 01:16 UTC
Hi

A colleague of mine is trying to use this extension to make backups, however they're getting the dotnet error in the screen clip. Is there possibly something that needs to be installed so the TMDL proxy will run? I've tried uninstalling the extension and along with logging out and back in, but neither seem to have fixed this.

![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/62320770/7dab5e2d-2d41-48df-a1b3-f5e2d4ea543f)

**Comment by gbrueckl** [comment] 2023-12-18 08:09
please also check the [Prerequisites](https://github.com/gbrueckl/PowerBI-VSCode?tab=readme-ov-file#prerequisites) you also need to install the dotnet framework

however, I am just running some other tests to find out some other potential dependencies here as it does not seem to be the only thing thats required

**Comment by samaguire** [comment] 2023-12-18 09:01
Ah. I missed the prerequisites under the TMDL section. I'll get ASP.Net installed and try again. 🙏

Regards
Stephen

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by samaguire** [comment] 2023-12-18 20:39
Okay, so I setup a Sandbox machine for this.

I used the prerequisite link for ASP.NET which took me to version 7. I installed the latest versions of both the ASP.NET Hosting Bundle and the full SDK of the latest .NET 7 and I'm still getting the same error.

I followed your link to the other thread and ran the code `dotnet 'c:\Users\WDAGUtilityAccount\.vscode\extensions\gerhardbrueckl.powerbi-vscode-1.3.0\resources\TMDLProxy\TMDLVSCodeConsoleProxy.dll', '55000', 
'pdEGcf5QfZATl27sdGhMzWIygDfnftUAplc08YfAapb8FyFedg60U5pd7rSomyGG'`

which gave the message

![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/62320770/0d872647-8729-4421-9ed6-d07312ce0e8e)

So, i installed the latest .NET 6 ASP.NET Hosting Bundle and BINGO!

![image](https://github.com/gbrueckl/PowerBI-VSCode/assets/62320770/c4620386-9bc1-446b-ad2b-3fd28f297713)


I reset the Sandbox and installed just the .NET 6 ASP.NET Hosting Bundle and it worked perfectly! Seems you need to install this specific version to get it to work. https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.25-windows-hosting-bundle-installer

**Comment by gbrueckl** [comment] 2023-12-18 20:50
I just did about the same thing :D 
Also I changed the framework in the underlying code to 7 so future version will require .Net Framework 7
In addition it also seems that you need to install .NET Desktop Runtime as otherwise the popup for authentication does not surface and you will get an authentication error

could you also verify this with .net 6?
e.g. if you simply try to `Edit TMDL` on any of your datasets?

I will update the docs accordingly and do another release - probably today

**Comment by samaguire** [comment] 2023-12-18 22:39
Okay. So I tried again, but looks like you've updated to the version, as I needed to use .NET 7 to get the TMDL server to load and download the TMDL for a model.

**Comment by gbrueckl** [comment] 2023-12-19 09:26
yes, with `v1.3.1` which was released yesterday I upgraded everything to .NET Framework 7

but does it work for you know after installing all the .Net Framework 7 components?

**Comment by samaguire** [comment] 2023-12-19 20:42
Yes, it does as per the instructions in the updated readme. Thanks for the help.

I also tested installing just the SDK (which covers both ASP.NET Core and Desktop Runtime) and it worked. It might be simpler to have people just install the SDK.

**Comment by gbrueckl** [comment] 2024-01-04 13:30
will add a hint for the SDK to the documentation
closing this as the root cause is fixed now

**Closed by gbrueckl** 2024-01-04 13:30 UTC
